baseURL = 'https://kreedzt.github.io/rwr-imba-server-doc/'
# baseURL = 'https://kreedzt.github.io/'
languageCode = 'zh-cn'
title = 'RWR Imba Server Docs'
theme = 'hugo-theme-techdoc'
publishDir = 'docs'
