baseURL = 'https://kreedzt.github.io/rwr-imba-server-doc/'
# baseURL = 'https://kreedzt.github.io/'
languageCode = 'zh-cn'
title = 'RWR Imba Server Docs'
theme = 'hugo-theme-techdoc'
publishDir = 'docs'
sectionPagesMenu = "main"

# For theme
[params]
  description = "RWR Imba Server 服务器文档, 记录所有 imba 服务器内容"
  title = "RWR Imba Server Docs"
  github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
  version = "0.0.1"
  github_doc_repository = "https://github.com/Kreedzt/rwr-imba-server-doc"
  menu_style = ""
  dateformat = "2006-01-02"
  algolia_search_enable = true

[menu]
[[menu.main]]
  name = "主页"
  url = "/"
  weight = 1
[[menu.main]]
  name = 'GFLNP(少女前线)'
  url = '/gflnp/'
  weight = 2
[[menu.main]]
  name = 'Azur Lane(碧蓝航线)'
  url = '/azur_lane/'

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
